version: '2'
services:
  sa_share_db:
    image: mongo
    command: mongod --port 3504
    ports:
      - "3504:3504"
  sa_share_ms:
    build: .
    command: bash -c "sleep 40 && rm -f tmp/pids/server.pid && revel run sa_share_ms prod"
    ports:
      - "3002:3002"
    depends_on:
      - sa_share_db