#Test with: http://editor.swagger.io/

swagger: '2.0'
info:
  version: 1.0.0
  title: Users microservice
  description: Ruby + MySQL Database
  contact:
      name: Daniel Caceres
      email: daacaceressa@unal.edu.co
  license:
    name: Software Architecture 2017-II
host: 192.168.99.102:3000
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /users:
    post:
      summary: Creates a user
      operationId: createUser
      parameters:
        - name: user
          in: body
          required: true
          description: User Object
          schema:
            $ref: '#/definitions/User'
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorModel'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorModel'

  /users/sign_in:
    post:
      summary: Logs into the application
      operationId: createSession
      parameters:
        - name: user
          in: body
          required: true
          description: UserLogInfo Object
          schema:
            $ref: '#/definitions/UserLogInfo'
      responses:
        '201':
          description: Created
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorModel'    
            
  /users/validate_token:
    post:
      summary: Checks if the token is valid and has an user assigned to it
      operationId: validate_token
      parameters:
        - name: X-AUTH-TOKEN
          in: header
          type: string
          required: true
          description: Token generated by the application and passed as a header when the user logs into the application
      responses:
        '202':
          description: Accepted
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (The token has expired)
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorModel' 
            
  /users/sign_out:
    delete:
      summary: Logs out of the application
      operationId: destroySession
      parameters:
        - name: X-AUTH-TOKEN
          in: header
          type: string
          required: true
          description: Token generated by the application and passed as a header when the user logs into the application
      responses:
        '200':
          description: Ok
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorModel' 

definitions:
# Users
  User:
    type: object
    properties:
      id:
        type: integer
      email:
        type: string
      password:
        type: string
      password_confirmation:
        type: string
        
  UserLogInfo:
    type: object
    properties:
      email:
        type: string
      password:
        type: string

# Errors
  ErrorModel:
    type: object
    required:
      - message
      - code
    properties:
      message:
        type: string
      code:
        type: number
      description:
        type: object